- name: "Web server set up"
  hosts: WebServer
  remote_user:  ubuntu
  gather_facts: no
  become: true

  tasks:

  - name: "install python"
    raw: "test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)"

  - name: "Install apache2"
    apt:
       name: apache2
       update_cache: yes
       state: latest

  - name: "Install php"
    apt:
       name: php
    become: true

  - name: "Install php-mysql"
    apt:
       name: php-mysql

  - name: "Install more php stuff"
    apt:
       name: libapache2-mod-php

  - name: "Installing last of php stuff"
    apt:
       name: php-mcrypt

  - name: "Restart apache2"
    service:
       name: apache2
       state: restarted

  - name: "install git"
    apt:
       name: git
       update_cache: yes
       state: latest

  - name: "Install mysql-client"
    apt:
       name: mysql-client
       state: present
       update_cache: yes

  - name: "Delete directory"
    file:
       path: /var/www/html
       state: absent

  - name: "Create directory"
    file:
        path: /var/www/html
        state: directory
        mode: 0777
    register: create

  - name: "git repo"
    git:
       repo: 'https://github.com/doc-vu/phpMySQLapp.git'
       dest: /var/www/html
    register: git_finished
    when: create.changed

  - name: "Make sure owned by www-data"
    file:
       path: /var/www/html/
       owner: www-data
       group: www-data
       recurse: yes
    when: git_finished.changed

  - name: "Configuring application through shell"
    shell: |
        data=$(tail -1 InventoryOnWebServer  | awk '{ print $1 }')
        sed -i -e "s/127.0.0.1/${data}/g" /var/www/html/books/includes/bookDatabase.php
        sed -i -e "s/127.0.0.1/${data}/g" /var/www/html/movies/includes/movieDatabase.php
